// constants/locations.ts
export const COVERED_MUNICIPALITIES = [
  'Buenavista',
  'Nasipit',
  'Carmen',
  'Kitcharao',
  'Santiago',
  'Tubay',
  'Magallanes',
  'Jabonga',
];

export const DELIVERY_FEES: Record<string, number> = {
  Buenavista: 50,
  Nasipit: 70,
  Carmen: 90,
  Kitcharao: 95,
  Santiago: 90,
  Tubay: 85,
  Magallanes: 100,
  Jabonga: 110,
};

export const MUNICIPALITIES_WITH_BARANGAYS: Record<string, string[]> = {
  Buenavista: [
    'Poblacion',
    'Afga',
    'Antipaz',
    'Aras-asan',
    'Baliwasan',
    'Buhang',
    'Caloc-an',
    'Hanagdong',
    'Katugasan',
    'La Fraternidad',
    'Lawigan',
    'Magsaysay',
    'Mandangoa',
    'Matabao',
    'Napo',
    'Pinayagan Norte',
    'Pinayagan Sur',
    'Rizal',
    'San Agustin',
    'San Isidro',
    'San Jose',
    'San Vicente',
    'Sangay',
    'Santo Rosario',
    'Tagbayani',
    'Tinigbasan',
    'Victory',
  ],
  Nasipit: [
    'Poblacion 1',
    'Poblacion 2',
    'Poblacion 3',
    'Aclan',
    'Amontay',
    'Ata-atahon',
    'Barangay 1',
    'Barangay 2',
    'Camagong',
    'Cubi-cubi',
    'Culit',
    'Jaguimitan',
    'Kinabjangan',
    'Punta',
    'San Isidro',
    'Talisay',
    'Tungao',
  ],
  Carmen: ['Poblacion', 'Cahayagan', 'San Agustin', 'Rojales', 'Tagcatong'],
  Kitcharao: ['Poblacion', 'Bangayan', 'Canaway', 'Crossing', 'Songkoy'],
  Santiago: ['Poblacion 1', 'Poblacion 2', 'Jagupit', 'Curva', 'San Isidro'],
  Tubay: ['Poblacion', 'Doce Martires', 'La Fraternidad', 'Binuangan', 'Tinigbasan'],
  Magallanes: ['Poblacion', 'Buhang', 'Caloc-an', 'Guiasan', 'Santo Nino'],
  Jabonga: ['Poblacion', 'A. Beltran', 'Baleguian', 'Colorado', 'Libas'],
};

export const isInCoverageArea = (municipality: string): boolean => {
  return COVERED_MUNICIPALITIES.includes(municipality);
};
